---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: false

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-0f2b4fc905b0bd1f1  # centos
      keypair: newohio # pem file name
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: subnet-341cfd5f
         assign_public_ip: yes
      register: ec2
