---

- hosts: demo
  become: yes
  tasks:

  - name: nodejs dependency
    shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -

  - name: Install Packages
    yum: name={{ item }} update_cache=yes state=present
    with_items:
      - nodejs
      - npm
      
